### ISSUE TITLE
Catalog of my things

### ISSUE THREAD

**Issue by barakadanny** [X-Elie-X/catalog-of-my-things#25]
# Note 🔖 
This project is being developed by:
-  [Baraka Danny](https://github.com/barakadanny) 
- [Elie Harfouche](https://github.com/X-Elie-X) 
- `Benjamin Kisenge`(Has abandoned )

Link to the Project distribution  [Kanban board](https://github.com/X-Elie-X/catalog-of-my-things/projects/1)

Happy Coding 🥂

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Kindly add a task for "adding unit testing for the label and book classes".
- [ ] Kindly add a task for "preserving data for the label and book classes".
- [ ] Please make sure that the tasks are assigned equally between team members when it comes to points assigned. The difference between team members' points shouldn't be large. Currently here's an overview of each team member and the points assigned to each:
   | Team member | Points |
   | --- | --- |
   | @barakadanny | 10pts |
   | @iambenkis | 6pts |
   | @X-Elie-X | 11.5pts |
   
- Please make sure that the difference in points between team members doesn't exceed 5pts at most.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by FrederickMih** [comment]
## Hi :raising_hand_man: @barakadanny, @X-Elie-X, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Tasks are assigned equally between team members :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
